// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"goboot/pkg"
	"goboot/pkg/config"
	"goboot/pkg/gin"
	"goboot/pkg/logger"
)

// Injectors from wire.go:

func CreateApp(cf string) (*app.App, error) {
	configManager := config.NewConfigManager()
	manager, err := logger.NewManager(configManager)
	if err != nil {
		return nil, err
	}
	option, err := gin.NewOption(configManager)
	if err != nil {
		return nil, err
	}
	server, err := gin.NewServer(manager, configManager, option)
	if err != nil {
		return nil, err
	}
	appApp, err := app.New(cf, manager, server)
	if err != nil {
		return nil, err
	}
	return appApp, nil
}

// wire.go:

var providerSet = wire.NewSet(config.ProviderSet, logger.ProviderSet, gin.ProviderSet, app.ProviderSet)
