// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ahrtolia/goboot/pkg"
	"github.com/ahrtolia/goboot/pkg/config"
	"github.com/ahrtolia/goboot/pkg/gin"
	"github.com/ahrtolia/goboot/pkg/gorm"
	"github.com/ahrtolia/goboot/pkg/logger"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateApp(configFile2 string) (*app.App, error) {
	options := config.NewOptions()
	configManager := config.InitConfigManager(options)
	zapLogger, err := logger.NewLogger(configManager)
	if err != nil {
		return nil, err
	}
	option, err := gin.NewOption(configManager)
	if err != nil {
		return nil, err
	}
	server, err := gin.NewServer(zapLogger, configManager, option)
	if err != nil {
		return nil, err
	}
	appApp, err := app.New(configManager, server)
	if err != nil {
		return nil, err
	}
	return appApp, nil
}

// wire.go:

var (
	configSet = wire.NewSet(config.ProviderSet, config.NacosProvider)

	loggerSet = wire.NewSet(logger.ProviderSet)

	httpSet = wire.NewSet(gin.ProviderSet)

	dbSet = wire.NewSet(gorm.ProviderSet)

	appSet = wire.NewSet(app.ProviderSet)

	globalSet = wire.NewSet(
		configSet,
		loggerSet,
		httpSet,
		dbSet,
		appSet,
	)
)
